#!/usr/bin/env python3
"""Build the student-facing readme.md from the repository's teaching materials."""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'readme.md'
DIRECTIONS = {
    'КБ': '10.05.01 «Компьютерная безопасность»',
    'ИВТ': '09.03.01 «Информатика и вычислительная техника»',
    'ПИ': '09.03.04 «Программная инженерия»',
}
SECTIONS = {'Лекции': '📖', 'Практики': '🧪', 'КР': '📝', 'РПД и ФОС': '📋'}
FORMATS = {'.md': 'Markdown', '.pdf': 'PDF', '.doc': 'Word', '.docx': 'Word',
           '.ppt': 'PowerPoint', '.pptx': 'PowerPoint', '.xls': 'Excel',
           '.xlsx': 'Excel', '.csv': 'CSV', '.txt': 'Текст', '.ipynb': 'Jupyter'}
EXCLUDED_DIRS = {'.git', '.github', '.agents', 'scripts', '__pycache__',
                 '.venv', 'venv', 'node_modules', '.idea', '.vscode', '.pytest_cache'}


def relative_url(path: Path) -> str:
    return './' + quote(path.relative_to(ROOT).as_posix(), safe='/._-')


def escape(text: str) -> str:
    """Keep document headings safe inside Markdown tables and link labels."""
    text = html.escape(re.sub(r'\s+', ' ', text), quote=False)
    return re.sub(r'([\\`*\[\]|])', r'\\\1', text)


def markdown_title(path: Path) -> str | None:
    if path.suffix.lower() != '.md':
        return None
    fence = None
    with path.open(encoding='utf-8-sig', errors='replace') as source:
        for index, line in enumerate(source):
            if index >= 250:
                break
            stripped = line.strip()
            marker = re.match(r'^(`{3,}|~{3,})', stripped)
            if marker:
                token = marker.group(1)
                if fence is None:
                    fence = token
                elif token[0] == fence[0] and len(token) >= len(fence):
                    fence = None
                continue
            if fence:
                continue
            heading = re.match(r'^#\s+(.+?)\s*$', stripped)
            if heading:
                return re.sub(r'\s+#+$', '', heading.group(1)).strip()
    return None


def title(path: Path) -> str:
    return markdown_title(path) or re.sub(r'[_-]+', ' ', path.stem).strip()


def natural_key(path: Path) -> list:
    return [int(part) if part.isdigit() else part.casefold()
            for part in re.split(r'(\d+)', path.relative_to(ROOT).as_posix())]


def documents(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    return sorted((p for p in directory.rglob('*')
                   if p.is_file() and p.suffix.lower() in FORMATS
                   and p.name.casefold() != 'readme.md'
                   and not any(part.startswith('.') or part in EXCLUDED_DIRS
                               for part in p.relative_to(ROOT).parts)), key=natural_key)


def badge(label: str, value: str | int, color: str) -> str:
    # Shields treats doubled underscores and hyphens as literal characters.
    def encode(value: str | int) -> str:
        return quote(str(value).replace('_', '__').replace('-', '--'), safe='')
    url = f'https://img.shields.io/badge/{encode(label)}-{encode(value)}-{color}?style=flat-square'
    return f'  <img src="{url}" alt="{html.escape(f"{label}: {value}", quote=True)}">'


def generate() -> str:
    directions = [ROOT / name for name in DIRECTIONS if (ROOT / name).is_dir()]
    all_documents = [p for direction in directions for p in documents(direction)]
    lectures = sum(len(documents(d / 'Лекции')) for d in directions)
    practices = sum(len(documents(d / 'Практики')) for d in directions)
    lines = [
        '<!-- Generated by scripts/generate_readme.py. Edit the generator, not this file. -->',
        '', '<div align="center">', '', '# Операционные системы', '',
        '**Устройство ОС · системное программирование · компьютерная безопасность**', '',
        'Учебные материалы для студентов: от знакомства с операционной системой',
        'до практической работы с процессами, памятью и механизмами защиты.', '',
        '<p>', badge('Направления', len(directions), '6366f1'),
        badge('Лекции', lectures, '2563eb'), badge('Практики', practices, '0891b2'),
        badge('Материалы', len(all_documents), '475569'), '</p>', '',
        '[Выбрать направление](#направления-подготовки) · [Открыть материалы](#каталог-материалов) · [Начать работу](#как-пользоваться)',
        '', '</div>', '', '---', '', '## Направления подготовки', '',
        'Выберите своё направление — ссылки ведут непосредственно в нужный раздел.', '',
        '| Направление | Лекции | Практики | Контрольные работы | РПД и ФОС |',
        '| :--- | :---: | :---: | :---: | :---: |',
    ]
    for direction in directions:
        cells = [f'**[{direction.name}]({relative_url(direction)})**<br>{DIRECTIONS[direction.name]}']
        for section in SECTIONS:
            folder = direction / section
            count = len(documents(folder))
            cells.append(f'[Открыть · {count}]({relative_url(folder)})' if count else '—')
        lines.append('| ' + ' | '.join(cells) + ' |')
    lines += ['', '*Числа показывают количество опубликованных материалов; «—» означает, что раздел пока не заполнен.*',
              '', '## Как пользоваться', '',
              '1. **Выберите направление** в таблице выше.',
              '2. **Изучите лекцию** и откройте соответствующую практическую работу.',
              '3. **Подготовьте учебный стенд** по инструкции к первой практической работе своего направления.',
              '4. **Выполните задания и оформите отчёт** по требованиям конкретной работы.', '',
              'Материалы в Markdown можно читать прямо на GitHub. Для работы без интернета скачайте репозиторий через **Code → Download ZIP**.',
              '', '## Каталог материалов', '',
              'Список автоматически обновляется при добавлении, переименовании и удалении учебных файлов.', '']
    for direction in directions:
        lines += [f'### {direction.name} · {DIRECTIONS[direction.name]}', '']
        items = documents(direction)
        if not items:
            lines += ['Материалы этого направления пока не опубликованы.', '']
            continue
        grouped = set()
        for section, icon in SECTIONS.items():
            files = documents(direction / section)
            grouped.update(files)
            if files:
                lines += render_catalog(f'{icon} {section}', files)
        other = [p for p in items if p not in grouped]
        if other:
            lines += render_catalog('📎 Дополнительные материалы', other)
    lines += ['---', '', '<details>', '<summary><b>⚙️ Автоматическое обновление README</b></summary>', '',
              'GitHub Actions запускает генератор после изменений в ветке `main`. '
              'Названия берутся из заголовков Markdown, остальные файлы отображаются по имени. '
              'Изображения, служебные файлы и вложенные README не включаются в каталог и счётчики.', '',
              'Чтобы изменить оформление этой страницы, редактируйте [`scripts/generate_readme.py`](./scripts/generate_readme.py). '
              'Ручные правки `readme.md` будут заменены при следующей генерации.', '',
              'Обновить страницу локально:', '', '```bash', 'python scripts/generate_readme.py', '```', '',
              'Проверить актуальность:', '', '```bash', 'python scripts/generate_readme.py --check', '```', '',
              'Workflow: [update-readme.yml](./.github/workflows/update-readme.yml).', '', '</details>', '']
    return '\n'.join(lines)


def render_catalog(label: str, files: list[Path]) -> list[str]:
    lines = ['<details open>', f'<summary><b>{label}</b> · {len(files)}</summary>', '',
             '| Материал | Формат |', '| :--- | :---: |']
    for path in files:
        lines.append(f'| [{escape(title(path))}]({relative_url(path)}) | {FORMATS[path.suffix.lower()]} |')
    return lines + ['', '</details>', '']


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='check freshness without writing')
    args = parser.parse_args()
    generated = generate()
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else ''
    if args.check:
        fresh = current == generated
        print('readme.md is up to date' if fresh else 'readme.md is out of date',
              file=sys.stdout if fresh else sys.stderr)
        return 0 if fresh else 1
    if current != generated:
        OUTPUT.write_text(generated, encoding='utf-8', newline='\n')
        print('readme.md updated')
    else:
        print('readme.md is already up to date')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
